repos:
  - repo: local
    hooks:
      # Hook to compile LaTeX using make
      - id: compile-tex
        name: Compile LaTeX with make
        entry: make notes
        language: system
        types: [tex]
        always_run: true

      # Hook to format LaTeX files with latexindent
      - id: format-latex
        name: Format LaTeX files (.tex and .sty) with latexindent
        entry: bash -c 'FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(tex|sty)$"); if [ -n "$FILES" ]; then latexindent -w $FILES; fi'
        language: system
        files: \.(tex|sty)$
